version: '3.4'

services:
  mongodb:
    image: mongo
    container: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: temperature
    volumes:
      - ./mongo-db:/data/db
    ports:
      - '27017-27019:27017-27019'

  